// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";

import * as AuthLoginRoute from "@/app/(auth)/login/page.info";
import * as AuthRegisterRoute from "@/app/(auth)/register/page.info";
import * as MainRoute from "@/app/(main)/page.info";
import * as MainTransactionsRoute from "@/app/(main)/transactions/page.info";
import * as ApiEndpointRoute from "@/app/api/[...endpoint]/route.info";
import * as DashboardRoute from "@/app/dashboard/page.info";

import { makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({}),
};

export const AuthLogin = makeRoute("/(auth)/login", {
  ...defaultInfo,
  ...AuthLoginRoute.Route,
});
export const AuthRegister = makeRoute("/(auth)/register", {
  ...defaultInfo,
  ...AuthRegisterRoute.Route,
});
export const Main = makeRoute("/(main)", {
  ...defaultInfo,
  ...MainRoute.Route,
});
export const MainTransactions = makeRoute("/(main)/transactions", {
  ...defaultInfo,
  ...MainTransactionsRoute.Route,
});
export const ApiEndpoint = makeRoute("/api/[...endpoint]", {
  ...defaultInfo,
  ...ApiEndpointRoute.Route,
});
export const Dashboard = makeRoute("/dashboard", {
  ...defaultInfo,
  ...DashboardRoute.Route,
});
